[package]
name = "devrc"
version = "0.2.0"
authors = ["Alex <github.com/lispython>"]
description = "devrc is an easy to use task automation tool on steroids for developers"
edition = "2018"
keywords = ["tasks", "automation", "makefile", "command-line"]
categories = ["command-line-utilities",  "development-tools", "config"]
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/devrc-hub/devrc"
repository = "https://github.com/devrc-hub/devrc"

include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md", "CHANGELOG.md"]


[dependencies]
env_logger = "0.8.2"
log = "0.4.11"
serde = { version = "1.0.123", features = ["derive"] }
serde_yaml = "0.8.17"
structopt = "0.3.21"

# yaml-merge-keys = "0.4.1"

# Simple crate for parsing user input.
# casual = "0.2.0"
dirs-next = "2.0.0"
# openssl = { version = "0.10.32", features = ["vendored"] }
# Not used yet
# reqwest = { version = "0.10.9", features = ["blocking", "json"] }
indexmap = { version="1.6.1", features = ["serde-1"] }
ansi_term = "0.12.1"
dotenv = "0.15.0"
tera = "1.6.1"
unicode-width = "0.1.8"
atty = "0.2.14"
tempfile = "3.2.0"
ctrlc = "3.1.8"
# For remote command execution
# ssh2 = "0.9.1"



[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3


[[bin]]
name = "devrc"
path = "src/main.rs"


[badges]
maintenance = { status = "actively-developed" }
