[workspace]

members = [
    "cli",
    "plugins"
]

resolver="2"

[profile.dev]
opt-level = 0
debug = 2
lto = false

[profile.test]
opt-level = 0
debug = 2
lto = false

[profile.release]
opt-level = 3
