[[cmd]]
name = "‘devrc -f ./devrcfiles/before_after.yml --list’ produces the correct list"
shell = "devrc -f ./devrcfiles/before_after.yml --list"
stdout = { file = "outputs/before_and_after_list_tasks.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "help"]


[[cmd]]
name = "‘devrc -f ./devrcfiles/before_after.yml -v test_1’ produces the correct output"
shell = "devrc -f ./devrcfiles/before_after.yml -v test_1"
stdout = { file = "outputs/before_and_after_execute_test_1_stdout.ansitxt" }
stderr = { file = "outputs/before_and_after_execute_test_1_stderr.ansitxt" }
status = 0
tags = [ "execute"]


[[cmd]]
name = "‘devrc -f ./devrcfiles/before_after.yml -v test_2’ produces the correct output"
shell = "devrc -f ./devrcfiles/before_after.yml -v test_2"
stdout = { file = "outputs/before_and_after_execute_test_2_stdout.ansitxt"}
stderr = { file = "outputs/before_and_after_execute_test_2_stderr.ansitxt" }
status = 0
tags = [ "execute"]
