[[cmd]]
# devrc create_spec "devrc -f xtests/devrcfiles/test_base.yml -- test_1" "test_base_test_1_1"
name = "‘devrc -f ./devrcfiles/test_base.yml -- test_1’ produces the correct output"
shell = "devrc -f ./devrcfiles/test_base.yml -- test_1"
stdout = { file = "outputs/test_base_test_1_1_stdout.ansitxt" }
stderr = { file = "outputs/test_base_test_1_1_stderr.ansitxt" }
status = 0
tags = [ "execute"]

[[cmd]]
# devrc create_spec "devrc -f xtests/devrcfiles/test_base.yml -- test_2" "test_base_test_2_1"
name = "‘devrc -f ./devrcfiles/test_base.yml -- test_2’ produces the correct output"
shell = "devrc -f ./devrcfiles/test_base.yml -- test_2"
stdout = { file = "outputs/test_base_test_2_1_stdout.ansitxt" }
stderr = { file = "outputs/test_base_test_2_1_stderr.ansitxt" }
status = 0
tags = [ "execute"]

[[cmd]]
# devrc create_spec "devrc -f xtests/devrcfiles/test_base.yml -- test_3" "test_base_test_3_1"
name = "‘devrc -f ./devrcfiles/test_base.yml -- test_3’ produces the correct output"
shell = "devrc -f ./devrcfiles/test_base.yml -- test_3"
stdout = { file = "outputs/test_base_test_3_1_stdout.ansitxt" }
stderr = { file = "outputs/test_base_test_3_1_stderr.ansitxt" }
status = 0
tags = [ "execute"]
